### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by coolapso**
adds missing " on anchor link

### CODE REVIEW

**Comment by coolapso** [comment]
There is not much information on what else should i do when opening a PR, therefore please let me know if there is anything i need to change. 

Thank you.

**Comment by jcubic** [comment]
Sorry but I don't like how the HTML looks right now. I would just add the missing quote and not remove one.

**Comment by coolapso** [comment]
@jcubic you are right, I am sorry. 

Just fixed it let me know if there's anything else.

**Comment by jcubic** [comment]
Thanks for the fix.

**Pull request merged**
