### PR TITLE
Corrected some of the typo in the code and added images to the codebl…

### PR DESCRIPTION
**Pull request by ezinneanne**
I corrected the typos in the code and added images to the codeblock

### CODE REVIEW

**Comment by jcubic** [comment]
Thanks for your PR. Good idea to put the images. But it would be great if:
* quotes for attributes were double quotes `"` not single quotes `'`
* files are pretty random, if there is no way to give them meaningful names maybe `screenshot-001.png` (lowercase is safer on the web, and number 001 will be future-proof)

It seems that the copy example is missing copy function to create a screenshot.

You can use:
```javascript
function copy(src, dest) {
   if (src === 'nonexistent') {
      return false;
   }
   return true;
   // NOTE: for this dummy example, you can use
   // return src !== 'nonexistent';
}
```

And test:

```
copy --src nonexistent --dest anything
copy --src something --dest example
```

Thanks again for taking the time to create a PR to update the Documentation. Good documentation is a big problem of Open Source. You will be added to README when I call the script to update the avatars I usually do this when I release a new version (it's partially automated but require a manual trigger).

**Comment by ezinneanne** [comment]
I have made the corrections

**Comment by jcubic** [comment]
Thanks and sorry I was not clear, I wanted you to add a function I've added in a comment not related to the old code. So the code supposes to be:
```javascript
$('body').terminal({
    copy: function(...args) {
        var options = $.terminal.parse_options(args);
        if (options.dest && options.src) {
            if (copy(options.src, options.dest)) {
                this.echo('[[;darkgreen;]successful]');
            } else {
                this.error('failed');
            }
        } else {
            this.echo('usage\ncopy --dest &lt;file&gt; --src &lt;file&gt;');
        }
    }
}, {checkArity: false});

function copy(src, dest) {
   if (src === 'nonexistent') {
      return false;
   }
   return true;
   // NOTE: for this dummy example, you can use
   // return src !== 'nonexistent';
  }
}
```

because inside the code copy function was missing in this line:
```javascript
if (copy(options.src, options.dest)) {
```

`copy` was not defined so you probably was not able to create screenshot because it would throw an error that `copy` is not defined instead of "successful" or "failed" message

**Comment by ezinneanne** [comment]
I have made the corrections

**Comment by jcubic** [comment]
Thanks, good work.

**Comment by jcubic** [comment]
I've just checked the website, you probably didn't tested this locally. The images break the layout. They are way too big and are outside of the container on white background.

Next time if you create something please test if it actually works.

**Comment by jcubic** [comment]
It seems that you've put images outside of the `<div class="wrapper">` so they are not part of the layout.

**Comment by jcubic** [comment]
Also, the images are way too big for a such small layout. The are also broken because for no reason they are created on a big white background that doesn't look good with the current layout. I need to delete them.

**Comment by jcubic** [comment]
This is how the images look after fixing the layout:

Przechwycenie obrazu ekranu_2022-12-03_21-50-15

**Comment by jcubic** [comment]
Also note that the task was not to add screenshots but to look into Wiki and add more examples (actual source code).

**Comment by ezinneanne** [comment]
Oh am so sorry, I forgot to test it

**Pull request merged**
