### PR TITLE
Have added CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by rakshith6404**
PR/MR-Hacktoberfest2022

 I have added CONTRIBUTING.md file which could be really helpful and also there wasn't any documentation for the same in this repo 
i am looking forward for a merge :smile:

### CODE REVIEW

**Comment by jcubic** [comment]
Ok, but this actually doesn't explain how to contribute, you can find this information everywhere including google and Hacktoberfest resources page that you should read before you contribute.

Another issue is that directory after the clone doesn't have `.git` at the end and you don't show that you need to for the repo, which makes this whole tutorial totally wrong.

**Comment by jcubic** [comment]
If I would like to have a contribution file I would only want to have information that you should not change the style and only fix the HTML. So the intro is totally against what I would like to have in my contribution file.

**Comment by rakshith6404** [comment]
yeahh i get your point but i have added CONTRIBUTING.md which beginners or anything who are willing to contribute , could just view the steps in github itself . 
It would be helpful if they follow the steps in here itself.

**Comment by jcubic** [comment]
I don't see a reason for this type of file, you can find the information about contribution at https://hacktoberfest.com/participation/

**Pull request closed without merging**
