### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by marclaporte**

### CODE REVIEW

**Comment by jcubic** [comment]
@marclaporte Hey, can you update your url on your profile, it's not actual link it's just text (without http) GitHub is adding the http, but maybe you want https, FYI you also don't have redirect http -> https.

Because of this my script that is adding contributors is broken. My script is just dummy replacement.

**Comment by marclaporte** [comment]
@jcubic: done

**Comment by jcubic** [comment]
Thanks, you now have proper urls at:

https://github.com/jcubic/jquery.terminal-www
https://github.com/jcubic/jquery.terminal/tree/devel

in contributor sections. When there will be new version of the library you will also have url on npmjs.com.

**Comment by marclaporte** [comment]
@jcubic This is a great idea. More projects should do this :-)

**Comment by jcubic** [comment]
There is project that allow to add contributors by cli like [isomorphic-git](https://github.com/isomorphic-git/isomorphic-git) it was created by Kent C. Dots [all-contributors](https://github.com/all-contributors/all-contributors), my script have only code contributors (I grab them from the GitHub API).

**Pull request merged**
